name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file front/Dockerfile --tag front:v1
    - name: List docker images
      run: docker images
    - name: docker hub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag image to push
      run: docker tag front mehhlol/front:v1
    - name: docker hub push
      run: docker push mehhlol/front:v1
